/*
 * main.c — astools-mcp: MCP server over libastools.
 *
 * Transport: newline-delimited JSON-RPC 2.0 on stdio (one message per
 * line, no Content-Length framing — the current MCP stdio transport).
 * stdout carries protocol messages ONLY; every diagnostic goes to stderr.
 *
 * This is an in-tree binary: it links astools_static and includes
 * astools_internal.h for command-level access (registry descriptors,
 * ctx->cfg, ctx->tools_changed_flag).
 */

#include "astools_internal.h"
#include "json.h"

#include <stdlib.h>
#include <string.h>

#ifndef _WIN32
#include <signal.h>
#endif

/* ═══════════════════ default config template ═══════════════════ */

/* Written verbatim by --config-init: every key at its default, one
 * comment per key, parseable by config.c. */
static const char k_config_template[] =
    "// astools configuration (#astools_config).\n"
    "// Generated by `astools-mcp --config-init`. Every key is optional\n"
    "// and shown at its built-in default.\n"
    "#astools_config {\n"
    "  registry: {\n"
    "    // Ordered registry roots; trust is \"standard\" or \"full\".\n"
    "    paths: [{path: \"tools\", trust: \"standard\"}],\n"
    "    // Root watching: \"poll\" rescans on mtime changes; \"off\""
    " disables it.\n"
    "    watch: \"poll\",\n"
    "    // Minimum interval between watch polls (ISO 8601 duration).\n"
    "    poll_interval: r\"PT5S\",\n"
    "    // Lockfile policy: \"off\" | \"warn\" | \"enforce\".\n"
    "    pinning: \"warn\",\n"
    "    // Lockfile path, resolved against this config file's"
    " directory.\n"
    "    lock_path: \"astools.lock.xcdn\",\n"
    "    // Version pins for bare refs, e.g. [{tool: \"fs\", version:"
    " \"1.2.0\"}].\n"
    "    pins: [],\n"
    "  },\n"
    "  workspace: {\n"
    "    // Workspace root; \".\" resolves against the server's working"
    " directory.\n"
    "    root: \".\",\n"
    "    // Scratch directory; null means <root>/.astools/tmp.\n"
    "    scratch: null,\n"
    "  },\n"
    "  sandbox: {\n"
    "    // Sandbox level for invocations: \"none\" | \"basic\" |"
    " \"strict\".\n"
    "    default_level: \"basic\",\n"
    "    // Missing strict features: \"degrade\" (warn) or \"reject\".\n"
    "    strict_fallback: \"degrade\",\n"
    "    // Allow kind \"library\" tools from full-trust roots (host"
    " privileges).\n"
    "    allow_library: false,\n"
    "    // Absolute toolchain directories appended to the scrubbed PATH.\n"
    "    executable_paths: [],\n"
    "  },\n"
    "  grants: {\n"
    "    // Automatic workspace subtree grant: \"none\" | \"read\" |"
    " \"read-write\".\n"
    "    workspace_access: \"read-write\",\n"
    "    // Per-tool grants, e.g. [{tool: \"git\", proc: true}].\n"
    "    tools: [],\n"
    "  },\n"
    "  invocation: {\n"
    "    // Default per-invocation deadline (ISO 8601 duration).\n"
    "    timeout: r\"PT30S\",\n"
    "    // Maximum invocations running at once.\n"
    "    max_concurrent: 4,\n"
    "    // Tool stdout cap in bytes; exceeding it kills the"
    " invocation.\n"
    "    max_output_bytes: 1048576,\n"
    "    // Tool stderr capture cap in bytes (oldest half dropped when"
    " full).\n"
    "    stderr_max_bytes: 262144,\n"
    "    // Result-vs-schema checking: \"off\" | \"warn\" |"
    " \"enforce\".\n"
    "    result_validation: \"warn\",\n"
    "  },\n"
    "  catalog: {\n"
    "    // Default catalog detail: \"index\" | \"summary\" | \"full\".\n"
    "    level: \"summary\",\n"
    "    // Character budget for catalog renderings (0 = unlimited).\n"
    "    char_budget: 8000,\n"
    "    // Tool ids rendered before the rest of the catalog.\n"
    "    priority: [],\n"
    "  },\n"
    "  mcp: {\n"
    "    // Expose astools management tools over MCP.\n"
    "    management: false,\n"
    "  },\n"
    "  logging: {\n"
    "    // Log file path; null disables the file sink.\n"
    "    path: null,\n"
    "    // Verbosity: \"error\" | \"warn\" | \"info\" | \"debug\".\n"
    "    level: \"info\",\n"
    "    // Rotate the log when it exceeds this size (KiB).\n"
    "    max_size_kb: 5120,\n"
    "    // Rotated files kept besides the live log.\n"
    "    max_files: 3,\n"
    "    // fsync after every log line.\n"
    "    sync: false,\n"
    "    // Append one #invocation record per call to audit.xcdn.\n"
    "    audit: false,\n"
    "  },\n"
    "}\n";

/* ═══════════════════ management tools (mcp.management) ═══════════ */

typedef struct {
  const char *name;
  const char *desc;
  const char *schema_json;
  int read_only;
} mgmt_tool_def;

/* Names carry the reserved "astools_" prefix; a registry slug can never
 * contain '_', so with management enabled these are intercepted by
 * full name before the '<tool>_<command>' split and can never shadow a
 * real command. */
static const mgmt_tool_def k_mgmt_tools[] = {
    {"astools_registry_refresh",
     "Rescan all astools registry roots and republish the tool table.",
     "{\"type\":\"object\",\"properties\":{},"
     "\"additionalProperties\":false}",
     0},
    {"astools_tool_manifest",
     "Return the canonical xCDN manifest of one registered astools tool.",
     "{\"type\":\"object\",\"properties\":{\"ref\":{\"type\":\"string\","
     "\"description\":\"Tool id, optionally pinned as id@version.\"}},"
     "\"required\":[\"ref\"],\"additionalProperties\":false}",
     1},
    {"astools_sandbox_caps",
     "Report honest per-feature sandbox enforcement for this platform.",
     "{\"type\":\"object\",\"properties\":{\"strict\":{\"type\":"
     "\"boolean\",\"description\":\"Report the strict level instead of "
     "the default level.\"}},\"additionalProperties\":false}",
     1},
    {"astools_stats",
     "Return astools registry and invocation counters.",
     "{\"type\":\"object\",\"properties\":{},"
     "\"additionalProperties\":false}",
     1},
};

/* ═══════════════════ server state ═══════════════════ */

typedef struct {
  astools_ctx *ctx;
  int management;  /* config mcp.management, read once after open */
  int initialized; /* notifications/initialized received */
} mcp_server;

#define MCP_LEGACY_VERSION "2025-06-18"
#define MCP_MODERN_VERSION "2026-07-28"
/* stdio dispatch is strictly sequential, so response decoration can follow
 * the request currently being handled without per-request heap state. */
static int mcp_modern_response;

/* ═══════════════════ stdin line reader ═══════════════════ */

/* Hard cap on one JSON-RPC line. A single unterminated line must not drive
 * the host into memory exhaustion: bytes past the cap are consumed and
 * discarded, and the line is reported as too large (return -1), exactly as
 * the OOM path is. 64 MiB is far beyond any legitimate tools/call payload. */
#define MCP_MAX_LINE_BYTES (64u * 1024u * 1024u)

/* Read one '\n'-terminated line (terminator not stored). Returns 1 when a
 * line is in b (possibly empty), 0 on EOF with nothing pending, -1 when
 * the line could not be held (OOM or over the cap; it is still fully
 * consumed to the newline so the stream stays framed). */
static int read_line(astools_buf *b) {
  int ch, bad = 0;
  b->len = 0;
  if (b->data) b->data[0] = '\0';
  for (;;) {
    ch = getc(stdin);
    if (ch == EOF) {
      if (bad) return -1;
      return b->len > 0 ? 1 : 0;
    }
    if (ch == '\n') return bad ? -1 : 1;
    if (!bad && b->len >= MCP_MAX_LINE_BYTES) bad = 1;
    if (!bad && astools_buf_appendc(b, (char)ch) != ASTOOLS_OK) bad = 1;
  }
}

static int line_blank(const char *s, size_t n) {
  size_t i;
  for (i = 0; i < n; i++)
    if (s[i] != ' ' && s[i] != '\t' && s[i] != '\r') return 0;
  return 1;
}

/* ═══════════════════ JSON-RPC output ═══════════════════ */

/* jx_string with a fallback for hostile non-UTF-8 input (tool output and
 * engine messages are untrusted bytes; the codec rejects invalid UTF-8). */
static jx_value *jx_string_or(const char *s, const char *fallback) {
  jx_value *v = jx_string(s ? s : fallback);
  if (!v && s) v = jx_string(fallback);
  return v;
}

/* Serialize + write one protocol line; consumes v. stdout is protocol:
 * nothing else is ever written to it. */
static void emit_json(jx_value *v) {
  char *s;
  if (!v) return;
  s = jx_write(v, 0);
  jx_free(v);
  if (!s) return;
  fputs(s, stdout);
  fputc('\n', stdout);
  fflush(stdout);
  free(s);
}

/* {"jsonrpc":"2.0","id":<id-or-null>}; NULL on allocation failure. */
static jx_value *envelope(const jx_value *id) {
  jx_value *m = jx_object();
  int bad = 0;
  if (!m) return NULL;
  bad |= jx_object_set(m, "jsonrpc", jx_string("2.0"));
  bad |= jx_object_set(m, "id", id ? jx_clone(id) : jx_null());
  if (bad) {
    jx_free(m);
    return NULL;
  }
  return m;
}

static int decorate_modern_result(jx_value *result) {
  jx_value *meta, *info;
  int bad = 0;
  if (!result || jx_typeof(result) != JX_OBJECT) return -1;
  meta = jx_object();
  info = jx_object();
  if (!meta || !info) {
    jx_free(meta);
    jx_free(info);
    return -1;
  }
  bad |= jx_object_set(info, "name", jx_string("astools-mcp"));
  bad |= jx_object_set(info, "version", jx_string(ASTOOLS_VERSION));
  bad |= jx_object_set(meta, "io.modelcontextprotocol/serverInfo", info);
  bad |= jx_object_set(result, "resultType", jx_string("complete"));
  bad |= jx_object_set(result, "_meta", meta);
  return bad ? -1 : 0;
}

/* Consumes result. */
static void reply_result(const jx_value *id, jx_value *result) {
  if (mcp_modern_response && decorate_modern_result(result) != 0) {
    jx_free(result);
    return;
  }
  jx_value *m = envelope(id);
  if (!m) {
    jx_free(result);
    return;
  }
  if (jx_object_set(m, "result", result) != 0) {
    jx_free(m);
    return;
  }
  emit_json(m);
}

/* Consumes data (may be NULL). id == NULL replies with id null (-32700). */
static void reply_error(const jx_value *id, int code, const char *message,
                        jx_value *data) {
  jx_value *m = envelope(id);
  jx_value *e = jx_object();
  int bad = 0;
  if (!m || !e) {
    jx_free(m);
    jx_free(e);
    jx_free(data);
    return;
  }
  bad |= jx_object_set(e, "code", jx_int(code));
  bad |= jx_object_set(e, "message",
                       jx_string_or(message, "error (non-UTF-8 message)"));
  if (data) bad |= jx_object_set(e, "data", data);
  bad |= jx_object_set(m, "error", e); /* owns e from here on */
  if (bad) {
    jx_free(m);
    return;
  }
  emit_json(m);
}

static jx_value *err_data(astools_err e) {
  jx_value *d = jx_object();
  if (!d) return NULL;
  if (jx_object_set(d, "astools_err", jx_string(astools_err_name(e))) != 0) {
    jx_free(d);
    return NULL;
  }
  return d;
}

/* Engine failure (≠ tool failure): JSON-RPC error with the astools
 * error name in data. */
static void reply_engine_error(mcp_server *s, const jx_value *id,
                               astools_err e) {
  const char *msg = astools_last_error(s->ctx);
  if (!msg || msg[0] == '\0') msg = astools_err_name(e);
  reply_error(id, -32000, msg, err_data(e));
}

/* ═══════════════════ JSON → xCDN argument conversion ═══════════════════ */

/* Bare-ident keys per assignment: [a-z_][a-z0-9_]*; anything else is
 * emitted as a quoted string. */
static int key_is_bare(const char *k) {
  size_t i;
  if (!k || k[0] == '\0') return 0;
  if (!((k[0] >= 'a' && k[0] <= 'z') || k[0] == '_')) return 0;
  for (i = 1; k[i] != '\0'; i++) {
    char ch = k[i];
    if (!((ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '_'))
      return 0;
  }
  return 1;
}

/* Quoted xCDN string literal; mirrors ser.c's escaping exactly so the MCP
 * layer and the engine emit identical text ('"', '\\', \n, \r, \t, other
 * control bytes as \u00XX; UTF-8 passes through). */
static astools_err xb_string(astools_buf *b, const char *s, size_t len) {
  astools_err e;
  size_t i;
  if (!s) len = 0;
  e = astools_buf_appendc(b, '"');
  for (i = 0; i < len && e == ASTOOLS_OK; i++) {
    unsigned char ch = (unsigned char)s[i];
    if (ch == '"')
      e = astools_buf_appends(b, "\\\"");
    else if (ch == '\\')
      e = astools_buf_appends(b, "\\\\");
    else if (ch == '\n')
      e = astools_buf_appends(b, "\\n");
    else if (ch == '\r')
      e = astools_buf_appends(b, "\\r");
    else if (ch == '\t')
      e = astools_buf_appends(b, "\\t");
    else if (ch < 0x20)
      e = astools_buf_printf(b, "\\u%04X", (unsigned)ch);
    else
      e = astools_buf_appendc(b, (char)ch);
  }
  if (e == ASTOOLS_OK) e = astools_buf_appendc(b, '"');
  return e;
}

/* Compact single-line xCDN literal for a JSON value. Depth-capped to
 * mirror the JSON codec (its parser caps at 64 as well). */
static astools_err jx_to_xcdn(const jx_value *v, astools_buf *b, int depth) {
  astools_err e;
  if (depth >= 64) return ASTOOLS_ERR_INVALID;
  switch (jx_typeof(v)) {
    case JX_NULL:
      return astools_buf_appends(b, "null");
    case JX_BOOL:
      return astools_buf_appends(b, jx_bool_value(v) ? "true" : "false");
    case JX_NUMBER:
      if (jx_is_int(v)) return astools_buf_printf(b, "%lld", jx_int_value(v));
      {
        char tmp[64];
        int n = snprintf(tmp, sizeof tmp, "%.17g", jx_double_value(v));
        if (n < 0 || n >= (int)sizeof tmp) return ASTOOLS_ERR_INVALID;
        e = astools_buf_appends(b, tmp);
        /* Keep float typing across the xCDN parser: bare "3" would
         * re-parse as an integer. */
        if (e == ASTOOLS_OK && strpbrk(tmp, ".eE") == NULL)
          e = astools_buf_appends(b, ".0");
        return e;
      }
    case JX_STRING:
      return xb_string(b, jx_string_value(v), jx_string_length(v));
    case JX_ARRAY: {
      size_t i, n = jx_array_len(v);
      e = astools_buf_appendc(b, '[');
      for (i = 0; i < n && e == ASTOOLS_OK; i++) {
        if (i > 0) e = astools_buf_appendc(b, ',');
        if (e == ASTOOLS_OK) e = jx_to_xcdn(jx_array_at(v, i), b, depth + 1);
      }
      if (e == ASTOOLS_OK) e = astools_buf_appendc(b, ']');
      return e;
    }
    case JX_OBJECT: {
      size_t i, n = jx_object_count(v);
      e = astools_buf_appendc(b, '{');
      for (i = 0; i < n && e == ASTOOLS_OK; i++) {
        const char *k = jx_object_key_at(v, i);
        if (i > 0) e = astools_buf_appendc(b, ',');
        if (e == ASTOOLS_OK) {
          if (key_is_bare(k))
            e = astools_buf_appends(b, k);
          else
            e = xb_string(b, k, k ? strlen(k) : 0);
        }
        if (e == ASTOOLS_OK) e = astools_buf_appendc(b, ':');
        if (e == ASTOOLS_OK)
          e = jx_to_xcdn(jx_object_value_at(v, i), b, depth + 1);
      }
      if (e == ASTOOLS_OK) e = astools_buf_appendc(b, '}');
      return e;
    }
  }
  return ASTOOLS_ERR_INVALID;
}

/* ═══════════════════ tools/list entry builders ═══════════════════ */

static jx_value *make_annotations(int read_only, int destructive,
                                  int idempotent, int open_world) {
  jx_value *a = jx_object();
  int bad = 0;
  if (!a) return NULL;
  bad |= jx_object_set(a, "readOnlyHint", jx_bool(read_only));
  bad |= jx_object_set(a, "destructiveHint", jx_bool(destructive));
  bad |= jx_object_set(a, "idempotentHint", jx_bool(idempotent));
  bad |= jx_object_set(a, "openWorldHint", jx_bool(open_world));
  if (bad) {
    jx_free(a);
    return NULL;
  }
  return a;
}

/* One MCP tool entry for a command of a resolved registry tool; NULL on
 * any failure (caller skips the command). */
static jx_value *tool_entry(const astools_tool *t, const astools_cmd *cmd) {
  char name[136]; /* id ≤ 32 + '_' + command ≤ 64 always fits */
  char *desc = NULL, *schema_text = NULL;
  jx_value *entry = NULL, *schema = NULL;
  int bad = 0;

  if (!t || !t->m || !t->m->id || !cmd || !cmd->name) return NULL;
  if (snprintf(name, sizeof name, "%s_%s", t->m->id, cmd->name) >=
      (int)sizeof name)
    return NULL;
  if (astools_mcp_description(t, cmd, &desc) != ASTOOLS_OK) return NULL;
  if (astools_jschema_input(cmd, &schema_text) != ASTOOLS_OK) {
    astools_free(desc);
    return NULL;
  }
  if (jx_parse(schema_text, strlen(schema_text), &schema) != 0) {
    astools_free(desc);
    astools_free(schema_text);
    return NULL;
  }
  astools_free(schema_text);

  entry = jx_object();
  if (!entry) {
    astools_free(desc);
    jx_free(schema);
    return NULL;
  }
  bad |= jx_object_set(entry, "name", jx_string(name));
  bad |= jx_object_set(entry, "description", jx_string_or(desc, ""));
  astools_free(desc);
  bad |= jx_object_set(entry, "inputSchema", schema);
  bad |= jx_object_set(entry, "annotations",
                       make_annotations(cmd->read_only ? 1 : 0,
                                        cmd->destructive ? 1 : 0,
                                        cmd->idempotent ? 1 : 0,
                                        t->m->perms.net ? 1 : 0));
  if (bad) {
    jx_free(entry);
    return NULL;
  }
  return entry;
}

static jx_value *mgmt_entry(const mgmt_tool_def *d) {
  jx_value *entry, *schema = NULL;
  int bad = 0;
  if (jx_parse(d->schema_json, strlen(d->schema_json), &schema) != 0)
    return NULL;
  entry = jx_object();
  if (!entry) {
    jx_free(schema);
    return NULL;
  }
  bad |= jx_object_set(entry, "name", jx_string(d->name));
  bad |= jx_object_set(entry, "description", jx_string(d->desc));
  bad |= jx_object_set(entry, "inputSchema", schema);
  bad |= jx_object_set(entry, "annotations",
                       make_annotations(d->read_only, 0, 1, 0));
  if (bad) {
    jx_free(entry);
    return NULL;
  }
  return entry;
}

/* ═══════════════════ tools/call result shape ═══════════════════ */

/* {"content":[{"type":"text","text":...}],"isError":...}. The text is the
 * result xCDN (or "<code>: <message>"); structuredContent is deliberately
 * omitted — the xCDN text IS the payload. NULL on allocation failure. */
static jx_value *call_result(const char *text, int is_error) {
  jx_value *res = jx_object(), *content = jx_array(), *item = jx_object();
  int bad = 0;
  if (!res || !content || !item) {
    jx_free(res);
    jx_free(content);
    jx_free(item);
    return NULL;
  }
  bad |= jx_object_set(item, "type", jx_string("text"));
  bad |= jx_object_set(item, "text",
                       jx_string_or(text, "(non-UTF-8 tool output)"));
  bad |= jx_array_push(content, item);
  bad |= jx_object_set(res, "content", content);
  bad |= jx_object_set(res, "isError", jx_bool(is_error));
  if (bad) {
    jx_free(res);
    return NULL;
  }
  return res;
}

static void reply_call_text(const jx_value *id, const char *text,
                            int is_error) {
  jx_value *r = call_result(text, is_error);
  if (!r) {
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }
  reply_result(id, r);
}

/* ═══════════════════ method: initialize / ping ═══════════════════ */

static void handle_initialize(const jx_value *id, const jx_value *params) {
  const jx_value *protocol = NULL;
  const char *ver = NULL;
  jx_value *result, *caps, *tools, *info;
  int bad = 0;
  if (!id) return;
  if (params) protocol = jx_object_get(params, "protocolVersion");
  if (protocol && jx_typeof(protocol) != JX_STRING) {
    reply_error(id, -32022, "unsupported MCP protocol version", NULL);
    return;
  }
  if (protocol) ver = jx_string_value(protocol);
  if (!ver) ver = MCP_LEGACY_VERSION;
  if (strcmp(ver, MCP_LEGACY_VERSION) != 0) {
    reply_error(id, -32022, "unsupported MCP protocol version", NULL);
    return;
  }
  result = jx_object();
  caps = jx_object();
  tools = jx_object();
  info = jx_object();
  if (!result || !caps || !tools || !info) {
    jx_free(result);
    jx_free(caps);
    jx_free(tools);
    jx_free(info);
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }
  bad |= jx_object_set(result, "protocolVersion",
                       jx_string_or(ver, MCP_LEGACY_VERSION));
  bad |= jx_object_set(tools, "listChanged", jx_bool(1));
  bad |= jx_object_set(caps, "tools", tools);
  bad |= jx_object_set(result, "capabilities", caps);
  bad |= jx_object_set(info, "name", jx_string("astools-mcp"));
  bad |= jx_object_set(info, "version", jx_string(ASTOOLS_VERSION));
  bad |= jx_object_set(result, "serverInfo", info);
  if (bad) {
    jx_free(result);
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }
  reply_result(id, result);
}

static jx_value *discover_result(void) {
  jx_value *result = jx_object();
  jx_value *versions = jx_array();
  jx_value *caps = jx_object();
  int bad = !result || !versions || !caps;
  bad |= jx_array_push(versions, jx_string(MCP_MODERN_VERSION));
  bad |= jx_array_push(versions, jx_string(MCP_LEGACY_VERSION));
  bad |= jx_object_set(caps, "tools", jx_object());
  bad |= jx_object_set(result, "supportedVersions", versions);
  bad |= jx_object_set(result, "capabilities", caps);
  bad |= jx_object_set(result, "instructions",
                       jx_string("Sandboxed local tool registry."));
  bad |= jx_object_set(result, "ttlMs", jx_int(3600000));
  bad |= jx_object_set(result, "cacheScope", jx_string("private"));
  if (bad) {
    jx_free(result);
    return NULL;
  }
  return result;
}

/* ═══════════════════ method: tools/list ═══════════════════ */

static void handle_tools_list(mcp_server *s, const jx_value *id) {
  char **ids = NULL;
  size_t n = 0, i;
  jx_value *tools, *result;
  astools_err e;

  e = astools_tool_list(s->ctx, &ids, &n);
  if (e != ASTOOLS_OK) {
    reply_engine_error(s, id, e);
    return;
  }
  tools = jx_array();
  if (!tools) {
    for (i = 0; i < n; i++) astools_free(ids[i]);
    astools_free(ids);
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }
  /* Deterministic order: tool list order, then manifest command order. */
  for (i = 0; i < n; i++) {
    astools_tool *t = NULL;
    size_t j;
    if (astools_registry_resolve(s->ctx, ids[i], &t) != ASTOOLS_OK)
      continue; /* skip unresolvable ids, never fail the whole list */
    if (t && t->m) {
      for (j = 0; j < t->m->commands_len; j++) {
        jx_value *entry = tool_entry(t, &t->m->commands[j]);
        if (entry) (void)jx_array_push(tools, entry); /* push owns entry */
      }
    }
    astools_tool_unref(t);
  }
  for (i = 0; i < n; i++) astools_free(ids[i]);
  astools_free(ids);

  if (s->management) {
    for (i = 0; i < sizeof k_mgmt_tools / sizeof k_mgmt_tools[0]; i++) {
      jx_value *entry = mgmt_entry(&k_mgmt_tools[i]);
      if (entry) (void)jx_array_push(tools, entry);
    }
  }

  result = jx_object();
  if (!result) {
    jx_free(tools);
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }
  if (jx_object_set(result, "tools", tools) != 0) { /* owns tools */
    jx_free(result);
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }
  reply_result(id, result);
}

/* ═══════════════════ method: tools/call ═══════════════════ */

/* Handle a management tool call; returns 1 when name matched (reply
 * sent), 0 to fall through to registry dispatch. */
static int mgmt_call(mcp_server *s, const jx_value *id, const char *name,
                     const jx_value *args) {
  astools_err e;

  if (strcmp(name, "astools_registry_refresh") == 0) {
    e = astools_registry_refresh(s->ctx);
    if (e != ASTOOLS_OK)
      reply_engine_error(s, id, e);
    else
      reply_call_text(id, "{refreshed: true}", 0);
    return 1;
  }

  if (strcmp(name, "astools_tool_manifest") == 0) {
    const jx_value *refv = args ? jx_object_get(args, "ref") : NULL;
    const char *ref = jx_string_value(refv);
    char *text = NULL;
    if (!ref) {
      reply_error(id, -32602, "astools_tool_manifest: string 'ref' required",
                  NULL);
      return 1;
    }
    e = astools_tool_manifest(s->ctx, ref, &text);
    if (e != ASTOOLS_OK) {
      reply_engine_error(s, id, e);
      return 1;
    }
    reply_call_text(id, text ? text : "null", 0);
    astools_free(text);
    return 1;
  }

  if (strcmp(name, "astools_sandbox_caps") == 0) {
    const jx_value *sv = args ? jx_object_get(args, "strict") : NULL;
    astools_sandbox_caps caps;
    astools_buf b;
    int strict = 0;
    if (sv) {
      if (jx_typeof(sv) != JX_BOOL) {
        reply_error(id, -32602,
                    "astools_sandbox_caps: 'strict' must be a boolean", NULL);
        return 1;
      }
      strict = jx_bool_value(sv);
    }
    memset(&caps, 0, sizeof caps);
    e = astools_get_sandbox_caps(s->ctx, strict, &caps);
    if (e != ASTOOLS_OK) {
      reply_engine_error(s, id, e);
      return 1;
    }
    astools_buf_init(&b);
    if (astools_buf_printf(&b,
                           "{fs_confinement: %s, net_deny: %s, "
                           "syscall_filter: %s, memory_cap: %s, "
                           "cpu_cap: %s, process_cap: %s, "
                           "privilege_drop: %s}",
                           caps.fs_confinement ? "true" : "false",
                           caps.net_deny ? "true" : "false",
                           caps.syscall_filter ? "true" : "false",
                           caps.memory_cap ? "true" : "false",
                           caps.cpu_cap ? "true" : "false",
                           caps.process_cap ? "true" : "false",
                           caps.privilege_drop ? "true" : "false") !=
        ASTOOLS_OK) {
      astools_buf_free(&b);
      reply_error(id, -32603, "out of memory", NULL);
      return 1;
    }
    reply_call_text(id, b.data, 0);
    astools_buf_free(&b);
    return 1;
  }

  if (strcmp(name, "astools_stats") == 0) {
    astools_stats st;
    astools_buf b;
    memset(&st, 0, sizeof st);
    e = astools_get_stats(s->ctx, &st);
    if (e != ASTOOLS_OK) {
      reply_engine_error(s, id, e);
      return 1;
    }
    astools_buf_init(&b);
    if (astools_buf_printf(
            &b,
            "{tools_total: %zu, tools_enabled: %zu, "
            "tools_unavailable: %zu, invocations: %zu, ok: %zu, "
            "failed: %zu, denied: %zu, timeouts: %zu, cancelled: %zu, "
            "last_refresh_unix: %lld, last_invocation_unix: %lld}",
            st.tools_total, st.tools_enabled, st.tools_unavailable,
            st.invocations, st.ok, st.failed, st.denied, st.timeouts,
            st.cancelled, (long long)st.last_refresh_unix,
            (long long)st.last_invocation_unix) != ASTOOLS_OK) {
      astools_buf_free(&b);
      reply_error(id, -32603, "out of memory", NULL);
      return 1;
    }
    reply_call_text(id, b.data, 0);
    astools_buf_free(&b);
    return 1;
  }

  return 0;
}

static void handle_tools_call(mcp_server *s, const jx_value *id,
                              const jx_value *params) {
  const jx_value *namev, *args;
  const char *name, *us;
  char *tool;
  astools_buf ab;
  astools_result res;
  astools_err e;

  namev = params ? jx_object_get(params, "name") : NULL;
  name = jx_string_value(namev);
  if (!name || name[0] == '\0') {
    reply_error(id, -32602, "tools/call: missing tool name", NULL);
    return;
  }
  args = params ? jx_object_get(params, "arguments") : NULL;
  if (args && jx_typeof(args) == JX_NULL) args = NULL;
  if (args && jx_typeof(args) != JX_OBJECT) {
    reply_error(id, -32602, "tools/call: arguments must be an object", NULL);
    return;
  }

  if (s->management && mgmt_call(s, id, name, args)) return;

  /* Slugs cannot contain '_', so the FIRST '_' splits bijectively
   * into <tool-id> and <command>. */
  us = strchr(name, '_');
  if (!us || us == name || us[1] == '\0') {
    reply_error(id, -32602, "tools/call: unknown tool name", NULL);
    return;
  }
  tool = astools_strndup(name, (size_t)(us - name));
  if (!tool) {
    reply_error(id, -32603, "out of memory", NULL);
    return;
  }

  astools_buf_init(&ab);
  if (!args)
    e = astools_buf_appends(&ab, "{}");
  else
    e = jx_to_xcdn(args, &ab, 0);
  if (e != ASTOOLS_OK) {
    astools_buf_free(&ab);
    free(tool);
    reply_error(id, -32603, "tools/call: cannot encode arguments", NULL);
    return;
  }

  memset(&res, 0, sizeof res);
  e = astools_invoke(s->ctx, tool, us + 1, ab.data, 0, &res);
  astools_buf_free(&ab);
  free(tool);

  if (e != ASTOOLS_OK) {
    /* Engine failure: JSON-RPC error, never conflated with tool
     * failure. */
    astools_result_free(&res);
    reply_engine_error(s, id, e);
    return;
  }

  if (res.ok) {
    reply_call_text(id, res.result_xcdn ? res.result_xcdn : "null", 0);
  } else {
    astools_buf tb;
    astools_buf_init(&tb);
    if (astools_buf_printf(&tb, "%s: %s",
                           res.error_code ? res.error_code : "error",
                           res.error_message ? res.error_message : "") !=
        ASTOOLS_OK) {
      astools_buf_free(&tb);
      astools_result_free(&res);
      reply_error(id, -32603, "out of memory", NULL);
      return;
    }
    reply_call_text(id, tb.data, 1);
    astools_buf_free(&tb);
  }
  astools_result_free(&res);
}

/* ═══════════════════ dispatch ═══════════════════ */

static void handle_message(mcp_server *s, const char *line, size_t len) {
  jx_value *msg = NULL;
  const jx_value *id;
  const jx_value *params;
  const jx_value *protocolv = NULL;
  const char *method;

  if (jx_parse(line, len, &msg) != 0) {
    reply_error(NULL, -32700, "parse error", NULL);
    return;
  }
  if (jx_typeof(msg) != JX_OBJECT) {
    reply_error(NULL, -32600, "invalid request", NULL);
    jx_free(msg);
    return;
  }
  id = jx_object_get(msg, "id");
  method = jx_string_value(jx_object_get(msg, "method"));
  params = jx_object_get(msg, "params");
  if (!method) {
    if (id) reply_error(id, -32600, "invalid request: missing method", NULL);
    jx_free(msg);
    return;
  }

  {
    const jx_value *meta = params && jx_typeof(params) == JX_OBJECT
                               ? jx_object_get(params, "_meta")
                               : NULL;
    protocolv = meta && jx_typeof(meta) == JX_OBJECT
                    ? jx_object_get(meta,
                        "io.modelcontextprotocol/protocolVersion")
                    : NULL;
    mcp_modern_response = protocolv && jx_typeof(protocolv) == JX_STRING &&
                          strcmp(jx_string_value(protocolv),
                                 MCP_MODERN_VERSION) == 0;
  }
  if (protocolv && !mcp_modern_response &&
      strcmp(method, "server/discover") != 0) {
    if (id) reply_error(id, -32022, "unsupported MCP protocol version", NULL);
    jx_free(msg);
    return;
  }

  if (strcmp(method, "initialize") == 0) {
    mcp_modern_response = 0;
    handle_initialize(id, params);
  } else if (strcmp(method, "server/discover") == 0) {
    if (id) {
      jx_value *r;
      mcp_modern_response = 1;
      r = discover_result();
      if (r) reply_result(id, r);
      else reply_error(id, -32603, "out of memory", NULL);
    }
  } else if (strcmp(method, "notifications/initialized") == 0) {
    s->initialized = 1;
  } else if (strcmp(method, "notifications/cancelled") == 0) {
    /* Requests are served synchronously: nothing is ever in flight when
     * a cancellation arrives, so it is ignored by design. */
  } else if (strcmp(method, "ping") == 0) {
    if (id) {
      jx_value *r = jx_object();
      if (r)
        reply_result(id, r);
      else
        reply_error(id, -32603, "out of memory", NULL);
    }
  } else if (strcmp(method, "tools/list") == 0) {
    if (id) handle_tools_list(s, id);
  } else if (strcmp(method, "tools/call") == 0) {
    if (id) handle_tools_call(s, id, params);
  } else if (id) {
    reply_error(id, -32601, "method not found", NULL);
  }
  /* id-less unknown methods are notifications: ignored per JSON-RPC. */
  jx_free(msg);
}

/* After each request: consume the registry's changed flag and emit
 * notifications/tools/list_changed. Suppressed until the client has sent
 * notifications/initialized (MCP lifecycle); the flag stays set so the
 * signal is delivered later, never lost. */
static void notify_tools_changed(mcp_server *s) {
  astools_ctx *c = s->ctx;
  int changed = 0;
  jx_value *m;
  int bad = 0;
  if (!s->initialized) return;
  os_rwlock_wrlock(&c->lock);
  if (c->tools_changed_flag) {
    c->tools_changed_flag = false;
    changed = 1;
  }
  os_rwlock_wrunlock(&c->lock);
  if (!changed) return;
  m = jx_object();
  if (!m) return;
  bad |= jx_object_set(m, "jsonrpc", jx_string("2.0"));
  bad |= jx_object_set(m, "method",
                       jx_string("notifications/tools/list_changed"));
  if (bad) {
    jx_free(m);
    return;
  }
  emit_json(m);
}

/* ═══════════════════ install root ═══════════════════ */

static char *path_dirname_dup(const char *p) {
  size_t i, cut = 0;
  int seen = 0;
  if (!p) return NULL;
  for (i = 0; p[i] != '\0'; i++) {
    if (p[i] == '/'
#ifdef _WIN32
        || p[i] == '\\'
#endif
    ) {
      cut = i;
      seen = 1;
    }
  }
  if (!seen) return astools_strdup(".");
  if (cut == 0) return astools_strdup("/");
  return astools_strndup(p, cut);
}

/* <exedir>/../share/astools/tools (POSIX) / <exedir>\tools (Windows),
 * used only when it exists as a directory; standard trust. */
static char *find_install_root(void) {
  char *exe = NULL, *dir = NULL, *root = NULL;
  os_stat_info st;
  if (os_exe_path(&exe) != ASTOOLS_OK || !exe) return NULL;
  dir = path_dirname_dup(exe);
  free(exe);
  if (!dir) return NULL;
#ifdef _WIN32
  root = os_path_join(dir, "tools");
#else
  root = os_path_join(dir, "../share/astools/tools");
#endif
  free(dir);
  if (!root) return NULL;
  memset(&st, 0, sizeof st);
  if (os_stat(root, &st) != ASTOOLS_OK || st.type != OS_FT_DIR) {
    free(root);
    return NULL;
  }
  return root;
}

/* ═══════════════════ --config-init ═══════════════════ */

static int run_config_init(const char *config_path) {
  char *dir;
  astools_err e;
  if (!config_path) {
    fprintf(stderr,
            "astools-mcp: --config-init requires --config <file>\n");
    return 2;
  }
  if (os_file_exists(config_path)) {
    fprintf(stderr, "astools-mcp: refusing to overwrite existing %s\n",
            config_path);
    return 1;
  }
  dir = path_dirname_dup(config_path);
  if (dir) {
    (void)os_mkdir_p(dir); /* best effort; the write reports failures */
    free(dir);
  }
  e = os_write_file(config_path, k_config_template,
                    sizeof k_config_template - 1);
  if (e != ASTOOLS_OK) {
    fprintf(stderr, "astools-mcp: cannot write %s (%s)\n", config_path,
            astools_err_name(e));
    return 1;
  }
  fprintf(stderr, "astools-mcp: wrote default config to %s\n", config_path);
  return 0;
}

/* ═══════════════════ main ═══════════════════ */

static void usage(FILE *f) {
  fputs("usage: astools-mcp [--root <dir>]... [--config <file>]\n"
        "                   [--workspace <dir>] [--config-init]\n"
        "\n"
        "  --root <dir>       add a standard-trust registry root\n"
        "  --config <file>    #astools_config file (missing = defaults)\n"
        "  --workspace <dir>  workspace root override\n"
        "  --config-init      write a commented default config to the\n"
        "                     --config path and exit (never overwrites)\n",
        f);
}

int main(int argc, char **argv) {
  const char *config = NULL, *workspace = NULL;
  const char **roots = NULL; /* borrowed from argv */
  size_t roots_n = 0, roots_cap = 0, ri;
  int want_config_init = 0;
  int i;
  char *install = NULL, *env_ws = NULL;
  const char **paths = NULL;
  astools_open_params p;
  astools_ctx *ctx = NULL;
  astools_err e;
  mcp_server srv;
  astools_buf line;

  for (i = 1; i < argc; i++) {
    const char *a = argv[i];
    if (strcmp(a, "--root") == 0 && i + 1 < argc) {
      if (roots_n == roots_cap) {
        size_t nc = roots_cap ? roots_cap * 2 : 8;
        const char **np = realloc((void *)roots, nc * sizeof *np);
        if (!np) {
          fprintf(stderr, "astools-mcp: out of memory\n");
          free((void *)roots);
          return 1;
        }
        roots = np;
        roots_cap = nc;
      }
      roots[roots_n++] = argv[++i];
    } else if (strcmp(a, "--config") == 0 && i + 1 < argc) {
      config = argv[++i];
    } else if (strcmp(a, "--workspace") == 0 && i + 1 < argc) {
      workspace = argv[++i];
    } else if (strcmp(a, "--config-init") == 0) {
      want_config_init = 1;
    } else if (strcmp(a, "--help") == 0) {
      usage(stderr);
      free((void *)roots);
      return 0;
    } else {
      usage(stderr);
      free((void *)roots);
      return 2;
    }
  }

  if (want_config_init) {
    int rc = run_config_init(config);
    free((void *)roots);
    return rc;
  }

#ifndef _WIN32
  /* A vanished client must never kill the server mid-write; writes then
   * fail with EPIPE and the loop ends at stdin EOF. */
  signal(SIGPIPE, SIG_IGN);
#endif

  if (config && !os_file_exists(config))
    fprintf(stderr, "astools-mcp: config %s not found; using built-in "
                    "defaults\n",
            config);

  /* Roots handed to astools_open (standard trust, highest precedence):
   * install root first, then --root flags. ASTOOLS_PATH and the config's
   * registry.paths still apply — config.c prepends the env var and
   * astools_open appends configured roots after these. */
  install = find_install_root();
  if (install || roots_n > 0) {
    size_t k = 0;
    paths = malloc((roots_n + 2) * sizeof *paths);
    if (!paths) {
      fprintf(stderr, "astools-mcp: out of memory\n");
      free(install);
      free((void *)roots);
      return 1;
    }
    if (install) paths[k++] = install;
    for (ri = 0; ri < roots_n; ri++) paths[k++] = roots[ri];
    paths[k] = NULL;
  }

  if (!workspace) {
    env_ws = os_env_dup("ASTOOLS_WORKSPACE");
    if (env_ws && astools_str_blank(env_ws)) {
      free(env_ws);
      env_ws = NULL;
    }
  }

  memset(&p, 0, sizeof p);
  p.registry_paths = (const char *const *)paths;
  p.config_path = config;
  /* Workspace resolution: --workspace ▷ ASTOOLS_WORKSPACE ▷
   * config workspace.root ▷ cwd. The config default "." resolves against
   * the process cwd — for the Agent Plugin that IS ${PLUGIN_DATA}, the
   * intended mutable-state anchor. */
  p.workspace_root = workspace ? workspace : env_ws;

  e = astools_open(&p, &ctx);
  free((void *)paths);
  free(install);
  free(env_ws);
  free((void *)roots);
  if (e != ASTOOLS_OK || !ctx) {
    fprintf(stderr, "astools-mcp: astools_open failed: %s\n",
            astools_err_name(e));
    return 1;
  }

  memset(&srv, 0, sizeof srv);
  srv.ctx = ctx;
  srv.management = ctx->cfg.mcp_management ? 1 : 0;

  /* The open-time scan flags the table as changed; the client has not
   * seen any list yet, so that first edge is not a change to announce. */
  os_rwlock_wrlock(&ctx->lock);
  ctx->tools_changed_flag = false;
  os_rwlock_wrunlock(&ctx->lock);

  astools_buf_init(&line);
  for (;;) {
    int r = read_line(&line);
    if (r == 0) break; /* stdin EOF: clean shutdown */
    if (r < 0) {
      reply_error(NULL, -32700, "request line too large", NULL);
    } else {
      size_t len = line.len;
      if (len > 0 && line.data[len - 1] == '\r') len--;
      if (!line_blank(line.data, len))
        handle_message(&srv, line.data ? line.data : "", len);
    }
    notify_tools_changed(&srv);
  }
  astools_buf_free(&line);
  astools_close(ctx);
  return 0;
}
